### ISSUE TITLE
Project 1 Program C

### ISSUE THREAD

**Issue by gavindennis2000** [gavindennis2000/Phase-1-Small-Group-9#3]
[PHASE1specificationV8.docx](https://github.com/user-attachments/files/17085700/PHASE1specificationV8.docx)
**Phase 1, Program C:** 
Program to Add Time Entries Ex Post Facto
This program should be named `Team9logEntryLater.cs`

**GOAL:**
Create a program that allows the user to create and manage logs for activities that have already occurred. 

This program shall:
- [x] Receive inputs from the user
- [x] Output information to the screen
- [x] Save log information in an external  `.csv` file in the form of `LastnameFirstnameLog.csv`
- [ ] Contain an executable `.exe` file that can be run on a windows machine
- [ ] Have a test suite that performs tests for all functions of the application

**REQUIRES:**
- [x] #9 
- [x] #7 
- [x] #8 
- [x] #10
